// <auto-generated />
using System;
using Logistica.Infrastructure.Persistence.PersistenceModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Logistica.Infrastructure.Migrations
{
    [DbContext(typeof(PersistenceDbContext))]
    partial class PersistenceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Logistica.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.PaqueteEntregaPersistence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DestinoDireccionCompleta")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("Destino_DireccionCompleta");

                    b.Property<double>("DestinoLatitud")
                        .HasColumnType("double precision")
                        .HasColumnName("Destino_Latitud");

                    b.Property<double>("DestinoLongitud")
                        .HasColumnType("double precision")
                        .HasColumnName("Destino_Longitud");

                    b.Property<string>("EstadoPaquete")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EtiquetaId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("RegistroLatitud")
                        .HasColumnType("double precision")
                        .HasColumnName("Registro_Latitud");

                    b.Property<double?>("RegistroLongitud")
                        .HasColumnType("double precision")
                        .HasColumnName("Registro_Longitud");

                    b.Property<DateTime?>("RegistroTimestampConfirmacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Registro_TimestampConfirmacion");

                    b.Property<string>("RegistroTipoPrueba")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Registro_TipoPrueba");

                    b.Property<string>("RegistroUrlEvidencia")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Registro_UrlEvidencia");

                    b.HasKey("Id");

                    b.HasIndex("EtiquetaId")
                        .HasDatabaseName("IX_Paquete_EtiquetaId");

                    b.ToTable("PaquetesEntrega");
                });

            modelBuilder.Entity("Logistica.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.PuntoEntregaPersistence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EstadoPunto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("PaqueteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RutaDistribucionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Secuencia")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RutaDistribucionId");

                    b.ToTable("PuntosEntrega");
                });

            modelBuilder.Entity("Logistica.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.RutaDistribucionPersistence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlmacenDireccionCompleta")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("Almacen_DireccionCompleta");

                    b.Property<double>("AlmacenLatitud")
                        .HasColumnType("double precision")
                        .HasColumnName("Almacen_Latitud");

                    b.Property<double>("AlmacenLongitud")
                        .HasColumnType("double precision")
                        .HasColumnName("Almacen_Longitud");

                    b.Property<string>("EstadoRuta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<Guid>("PersonalEntregaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("RutasDistribucion");
                });

            modelBuilder.Entity("Logistica.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.PuntoEntregaPersistence", b =>
                {
                    b.HasOne("Logistica.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.RutaDistribucionPersistence", "RutaDistribucion")
                        .WithMany("PuntosEntrega")
                        .HasForeignKey("RutaDistribucionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RutaDistribucion");
                });

            modelBuilder.Entity("Logistica.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.RutaDistribucionPersistence", b =>
                {
                    b.Navigation("PuntosEntrega");
                });
#pragma warning restore 612, 618
        }
    }
}
